apiVersion: v1
kind: Service
metadata:
  name: {{ include "skaffold-chart.fullname" . }}
  labels:
    {{- include "skaffold-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "skaffold-chart.selectorLabels" . | nindent 4 }}
