apiVersion: v1
kind: Service
metadata:
  name: {{ include "skaffold-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ .Values.fullnameOverride }}
