apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    # - image: skaffold-example
    #   docker:
    #     dockerfile: Dockerfile
    - image: skaffold-spring-boot-example
      jib: {}
  # local: {}

deploy:
  kubectl:
    manifests:
      - k8s-*