apiVersion: v1
kind: Service
metadata:
  name: skaffold-webflux-example-web
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: skaffold-webflux-example-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-webflux-example-web
spec:
  selector:
    matchLabels:
      app: skaffold-webflux-example-web
  template:
    metadata:
      labels:
        app: skaffold-webflux-example-web
    spec:
      containers:
      - name: skaffold-webflux-example-web
        image: skaffold-webflux-example
        ports:
          - containerPort: 8080
        imagePullPolicy: Never
