apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rxjavademo
build:
  artifacts:
  - image: skaffold-webflux-example
    jib:
      project: com.javademo:javademo
deploy:
  kubectl:
    manifests:
    - k8s-web.yaml
