apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rxjavademo
build:
  artifacts:
  - image: skaffold-webflux-example
    # custom:
    #   buildCommand: ./build.sh
    # docker:
    #   dockerfile: Dockerfile
    jib:
      project: com.javademo:javademo
  # cluster: {}
  local: {}
    
# deploy:
#   kubectl:
#     manifests:
#     - k8s-web.yaml

deploy:
  helm:
    releases:
      - name: my-release
        chartPath: ./skaffold-chart
        namespace: default
        artifactOverrides: 
          image: skaffold-webflux-example
        imageStrategy:
          helm: {}

test:
  - image: skaffold-webflux-example
    structureTests:
      - './structure-test/*'