apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rxjavademo
build:
  tagPolicy:
    envTemplate:
      template: "{{.FOO}}"
  artifacts:
  - image: skaffold-webflux-example
    # custom:
    #   buildCommand: ./scripts/build.sh
    # docker:
    #   dockerfile: Dockerfile
    jib:
      project: com.javademo:javademo
    # sync:
    #   manual:
    #     - dest: ./*.md
    #       src: /etc
    sync: 
      auto: true
  # cluster: {}
  local: {}
    
# deploy:
#   kubectl:
#     manifests:
#     - k8s-web.yaml

deploy:
  statusCheckDeadlineSeconds: 20
  helm:
    releases:
      - name: my-release
        chartPath: ./skaffold-chart
        namespace: default
        artifactOverrides: 
          image: skaffold-webflux-example
        imageStrategy:
          helm: {}

test:
  - image: skaffold-webflux-example
    structureTests:
      - './structure-test/*'
    custom:
      - command: ./scripts/test.sh
        timeoutSeconds: 60

portForward:
- resourceType: deployment
  resourceName: skaffold-webflux-example-web
  namespace: default
  port: 8080
  localPort: 8080      