apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffolddemo
build:
  artifacts:
  - image: skaffold-example
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
    - k8s-pod.yaml
