apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: es-manual
  name: es-manual
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-manual
  template:
    metadata:
      labels:
        app: es-manual
    spec:
      containers:
      - image: elasticsearch:7.8.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        resources: {}
        env:
          - name: discovery.type
            value: "single-node"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-manual
  name: es-manual
  namespace: default
spec:
  ports:
  - nodePort: 32743
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-manual
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost