apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: es-manual
  name: es-manual
  namespace: default
  resourceVersion: "921421"
  selfLink: /apis/apps/v1/namespaces/default/deployments/es-manual
  uid: 23500543-6863-4a4e-972f-3be7105bc8c6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: es-manual
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: es-manual
    spec:
      containers:
      - image: elasticsearch:7.8.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-manual
  name: es-manual
  namespace: default
  resourceVersion: "921782"
  selfLink: /api/v1/namespaces/default/services/es-manual
  uid: 6d6f2464-9e8c-48fa-aca6-d290bff0a6e9
spec:
  clusterIP: 10.110.150.180
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32743
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-manual
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost